using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Multiplay.Server.Data.Migrations
{
    /// <inheritdoc />
    public partial class PlayerIdToInt : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // AlterColumn generates ALTER COLUMN TYPE without a USING clause, which
            // Postgres rejects for text → integer. Use raw SQL with explicit USING.
            migrationBuilder.Sql("""
                ALTER TABLE "Players" ALTER COLUMN "Id" TYPE integer USING "Id"::integer;
                ALTER TABLE "Players" ALTER COLUMN "Id" DROP DEFAULT;
                ALTER TABLE "Players" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Id",
                table: "Players",
                type: "text",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer")
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
        }
    }
}
